### ISSUE TITLE
Accuracy in parsing

### ISSUE THREAD

**Issue by leileigan** [alejandrofcarrera/WKTParser-ObjC#1]
In my app,i used WKTParser to parse a string like LINESTRING (-86.300942 32.377447, -134.410467 58.302197, -112.097094 33.448097),but the result was unexpected，all numbers after the decimal point are omitted,so can you tell me the reason?thx!

**Comment by alejandrofcarrera** [comment]
Yes, you are right.

This bug has been fixed :)
